// quotes-data.js — 50 цитат из официальных материалов president.tj
window.QUOTES = [
  {
    "id": 1,
    "img": "assets/hero/01-president-official.jpg",
    "topic": "маориф",
    "quote": "Илм фурӯғи маърифат аст ва маърифат пешрафти инсоният мебошад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 12,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Суханронӣ бахшида ба Рӯзи дониш",
    "source": "https://president.tj/node/9731.20"
  },
  {
    "id": 2,
    "img": "assets/hero/02-istiqlol-flag.jpg",
    "topic": "маориф",
    "quote": "Соҳаи маориф ва баланд бардоштани мақоми омӯзгор яке аз масъалаҳои муҳимми ҷомеа мебошад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Суханронӣ бахшида ба Рӯзи дониш",
    "source": "https://president.tj/node/9731.20"
  },
  {
    "id": 3,
    "img": "assets/hero/03-vahdat-diplomacy.jpg",
    "topic": "маориф",
    "quote": "Аҳли маориф дар рушди нерӯи инсонӣ саҳми бевосита дорад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Суханронӣ бахшида ба Рӯзи дониш",
    "source": "https://president.tj/node/9731.20"
  },
  {
    "id": 4,
    "img": "assets/hero/04-kishovarzi.jpg",
    "topic": "маориф",
    "quote": "Пешрафти тамоми соҳаҳои ҳаёти ҷомеа ва давлат ба сатҳи рушди маориф вобастагии мустақим дорад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 12,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Суханронӣ бахшида ба Рӯзи дониш",
    "source": "https://president.tj/node/9731.20"
  },
  {
    "id": 5,
    "img": "assets/hero/05-president-young.jpg",
    "topic": "дониш",
    "quote": "Даврони донишҷӯӣ на танҳо марҳалаи зебои ҷавонӣ, балки айёми муҳими омӯзиш аст.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Суханронӣ бахшида ба Рӯзи дониш",
    "source": "https://president.tj/node/9731.20"
  },
  {
    "id": 6,
    "img": "assets/hero/06-zaboni-millat.jpg",
    "topic": "дониш",
    "quote": "Донишҷӯӣ айёми азхуд кардани илму дониш, касбу ҳунар ва васеъ намудани ҷаҳонбинӣ мебошад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Суханронӣ бахшида ба Рӯзи дониш",
    "source": "https://president.tj/node/9731.20"
  },
  {
    "id": 7,
    "img": "assets/hero/07-chehrahoyi-mondagor.jpg",
    "topic": "забон",
    "quote": "Донистани забонҳои хориҷӣ ба ташаккулу тавсеаи мафкура ва ҷаҳонбинии ҷавонон мусоидат мекунад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 12,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Суханронӣ бахшида ба Рӯзи дониш",
    "source": "https://president.tj/node/9731.20"
  },
  {
    "id": 8,
    "img": "assets/hero/08-davlatdori.jpg",
    "topic": "технология",
    "quote": "Донистани забонҳои хориҷӣ барои азхудкунии техникаву технологияҳои навтарин роҳи васеъ мекушояд.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Суханронӣ бахшида ба Рӯзи дониш",
    "source": "https://president.tj/node/9731.20"
  },
  {
    "id": 9,
    "img": "assets/hero/09-suhanroni.jpg",
    "topic": "ҷавонон",
    "quote": "Наврасону ҷавононро зарур аст, ки илм омӯзанд.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Тақдими туҳфаҳо ба 80 ятими кулл",
    "source": "https://www.president.tj/node/27716"
  },
  {
    "id": 10,
    "img": "assets/hero/10-nishon-tojikiston.jpg",
    "topic": "ҷавонон",
    "quote": "Ҷавонон бояд донишҳои замони муосирро аз худ намоянд.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 12,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Тақдими туҳфаҳо ба 80 ятими кулл",
    "source": "https://www.president.tj/node/27716"
  },
  {
    "id": 11,
    "img": "assets/hero/01-president-official.jpg",
    "topic": "ватандӯстӣ",
    "quote": "Ҷавонон бояд ҳамчун фарзандони содиқи Ватан ба халқу давлат хизмати шоиста намоянд.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Тақдими туҳфаҳо ба 80 ятими кулл",
    "source": "https://www.president.tj/node/27716"
  },
  {
    "id": 12,
    "img": "assets/hero/02-istiqlol-flag.jpg",
    "topic": "омӯзгор",
    "quote": "Омӯзгор дар раванди таълиму тарбия ҳуқуқи хато кардан надорад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Паёми Президенти Тоҷикистон",
    "source": "https://president.tj/node/8136"
  },
  {
    "id": 13,
    "img": "assets/hero/03-vahdat-diplomacy.jpg",
    "topic": "омӯзгор",
    "quote": "Тақдири насли ояндасоз ва пешбарандаи давлату ҷомеа дар дасти омӯзгор аст.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 12,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Паёми Президенти Тоҷикистон",
    "source": "https://president.tj/node/8136"
  },
  {
    "id": 14,
    "img": "assets/hero/04-kishovarzi.jpg",
    "topic": "омӯзгор",
    "quote": "Омӯзгор ҳамчун роҳнамои маънавӣ барои ба камол расонидани насли шоистаи даврон масъул аст.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Паёми Президенти Тоҷикистон",
    "source": "https://president.tj/node/8136"
  },
  {
    "id": 15,
    "img": "assets/hero/05-president-young.jpg",
    "topic": "маърифат",
    "quote": "Ба ҷаҳолат фақат маърифат муқовимат карда метавонад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Президенти Тоҷикистон",
    "source": "https://www.president.tj/node/2966"
  },
  {
    "id": 16,
    "img": "assets/hero/06-zaboni-millat.jpg",
    "topic": "маърифат",
    "quote": "Аҳли зиё пошандагони тухми илму дониш мебошанд.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 12,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Президенти Тоҷикистон",
    "source": "https://www.president.tj/node/2966"
  },
  {
    "id": 17,
    "img": "assets/hero/07-chehrahoyi-mondagor.jpg",
    "topic": "омӯзгор",
    "quote": "Пешрафту тараққиёти ҷомеа ба фаъолияти пурсамари омӯзгор вобаста аст.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Президенти Тоҷикистон",
    "source": "https://www.president.tj/node/2966"
  },
  {
    "id": 18,
    "img": "assets/hero/08-davlatdori.jpg",
    "topic": "технология",
    "quote": "Илму техника ва технология бо суръати кайҳонӣ пеш меравад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Президенти Тоҷикистон",
    "source": "https://www.president.tj/node/2966"
  },
  {
    "id": 19,
    "img": "assets/hero/09-suhanroni.jpg",
    "topic": "забон",
    "quote": "Забони давлатӣ яке аз арзишҳои бузурги миллӣ ва пояи давлатдории миллӣ мебошад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 12,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Суханронӣ ба муносибати Рӯзи забон",
    "source": "https://www.president.tj/node/2667"
  },
  {
    "id": 20,
    "img": "assets/hero/10-nishon-tojikiston.jpg",
    "topic": "забон",
    "quote": "Забони давлатӣ нишонаи возеҳи истиқлолияти сиёсӣ ва таҷассумгари таърихи халқи тоҷик аст.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Суханронӣ ба муносибати Рӯзи забон",
    "source": "https://www.president.tj/node/2667"
  },
  {
    "id": 21,
    "img": "assets/hero/01-president-official.jpg",
    "topic": "забон",
    "quote": "Забони тоҷикӣ рамзи ҳувияти миллӣ ва худогоҳиву худшиносии миллӣ мебошад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Суханронӣ ба муносибати Рӯзи забон",
    "source": "https://www.president.tj/node/2667"
  },
  {
    "id": 22,
    "img": "assets/hero/02-istiqlol-flag.jpg",
    "topic": "ваҳдат",
    "quote": "Забони тоҷикӣ яке аз омилҳои асосии муттаҳидкунанда ва пайвандгари миллат мебошад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 12,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Суханронӣ ба муносибати Рӯзи забон",
    "source": "https://www.president.tj/node/2667"
  },
  {
    "id": 23,
    "img": "assets/hero/03-vahdat-diplomacy.jpg",
    "topic": "забон",
    "quote": "Барои рушди забони давлатӣ заминаи мусоиди сиёсӣ, иҷтимоӣ ва фарҳангӣ фароҳам оварда шудааст.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Суханронӣ ба муносибати Рӯзи забон",
    "source": "https://www.president.tj/node/2667"
  },
  {
    "id": 24,
    "img": "assets/hero/04-kishovarzi.jpg",
    "topic": "истиқлолият",
    "quote": "Забон дар ҳама давру замонҳо яке аз омилҳои асосии пойдории истиқлолияти миллӣ мебошад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Суханронӣ ба муносибати Рӯзи забон",
    "source": "https://www.president.tj/node/2667"
  },
  {
    "id": 25,
    "img": "assets/hero/05-president-young.jpg",
    "topic": "фарҳанг",
    "quote": "Забони тоҷикӣ дар ҷаҳон ҳамчун забони илму адаб ва фарҳанги воло шӯҳрат дорад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 12,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Суханронӣ ба муносибати Рӯзи забон",
    "source": "https://www.president.tj/node/2667"
  },
  {
    "id": 26,
    "img": "assets/hero/06-zaboni-millat.jpg",
    "topic": "истиқлолият",
    "quote": "Неъмати пурқиматтарин ва дастоварди бузургтарини мо истиқлолият мебошад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Суханронӣ ба ифтихори 25-солагии истиқлолият",
    "source": "https://www.president.tj/node/12958"
  },
  {
    "id": 27,
    "img": "assets/hero/07-chehrahoyi-mondagor.jpg",
    "topic": "истиқлолият",
    "quote": "Истиқлолият рамзи соҳибдавлатӣ ва ватандории халқи сарбаланди мо мебошад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Суханронӣ ба ифтихори 25-солагии истиқлолият",
    "source": "https://www.president.tj/node/12958"
  },
  {
    "id": 28,
    "img": "assets/hero/08-davlatdori.jpg",
    "topic": "ватан",
    "quote": "Мо Ватани соҳибихтиёру озодамонро самимона дӯст медорем.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 12,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Суханронӣ ба ифтихори 25-солагии истиқлолият",
    "source": "https://www.president.tj/node/12958"
  },
  {
    "id": 29,
    "img": "assets/hero/09-suhanroni.jpg",
    "topic": "ваҳдат",
    "quote": "Барои ҳифзи сулҳу оромӣ ва тақвияти ваҳдати миллӣ мо бояд софдилона заҳмат кашем.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Суханронӣ ба ифтихори 25-солагии истиқлолият",
    "source": "https://www.president.tj/node/12958"
  },
  {
    "id": 30,
    "img": "assets/hero/10-nishon-tojikiston.jpg",
    "topic": "ватан",
    "quote": "Мардуми ватандӯсту заҳматкаши мо ба дастовардҳои аз ин ҳам бузургу таърихӣ қодиранд.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Суханронӣ ба ифтихори 25-солагии истиқлолият",
    "source": "https://www.president.tj/node/12958"
  },
  {
    "id": 31,
    "img": "assets/hero/01-president-official.jpg",
    "topic": "ваҳдат",
    "quote": "Ваҳдати миллӣ ва ҳифзи якпорчагии давлати миллӣ сарчашмаи асосии пешрафти миллат мебошанд.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 12,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Президенти Тоҷикистон",
    "source": "https://president.tj/node/9635"
  },
  {
    "id": 32,
    "img": "assets/hero/02-istiqlol-flag.jpg",
    "topic": "ваҳдат",
    "quote": "Ҳифзи истиқлолу озодии Ватан бояд вазифаи муқаддаси ҳар як шаҳрванд бошад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Президенти Тоҷикистон",
    "source": "https://www.president.tj/event_by_theme/internal_politics/national_unity/20983"
  },
  {
    "id": 33,
    "img": "assets/hero/03-vahdat-diplomacy.jpg",
    "topic": "ватандӯстӣ",
    "quote": "Эҳтироми рамзҳои давлатӣ ва фарҳанги миллӣ вазифаи муқаддаси ҳар як фарди бонангу номус аст.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Президенти Тоҷикистон",
    "source": "https://www.president.tj/event_by_theme/internal_politics/national_unity/20983"
  },
  {
    "id": 34,
    "img": "assets/hero/04-kishovarzi.jpg",
    "topic": "қонун",
    "quote": "Эҳтиром ва риояи Конститутсияву қонунҳо таъмини волоияти қонунро таъмин мекунад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 12,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Президенти Тоҷикистон",
    "source": "https://www.president.tj/event_by_theme/internal_politics/national_unity/20983"
  },
  {
    "id": 35,
    "img": "assets/hero/05-president-young.jpg",
    "topic": "илм",
    "quote": "Илм-фурӯғи маърифат озмунест барои рушди тафаккури техникӣ ва ҷаҳонбинии илмӣ.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Шарҳи амри озмуни «Илм-фурӯғи маърифат»",
    "source": "https://www.president.tj/node/30035"
  },
  {
    "id": 36,
    "img": "assets/hero/06-zaboni-millat.jpg",
    "topic": "илм",
    "quote": "Рушди тафаккури техникӣ ва тарғиби ҷаҳонбинии илмӣ вазифаи муҳим мебошад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Шарҳи амри озмуни «Илм-фурӯғи маърифат»",
    "source": "https://www.president.tj/node/30035"
  },
  {
    "id": 37,
    "img": "assets/hero/07-chehrahoyi-mondagor.jpg",
    "topic": "илм",
    "quote": "Пайвасти илм бо истеҳсолот ба пешрафти кишвар мусоидат мекунад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 12,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Шарҳи амри озмуни «Илм-фурӯғи маърифат»",
    "source": "https://www.president.tj/node/30035"
  },
  {
    "id": 38,
    "img": "assets/hero/08-davlatdori.jpg",
    "topic": "маориф",
    "quote": "Ҷалби хонандагону донишҷӯён ба омӯзиши фанҳои риёзӣ, дақиқ ва табиӣ муҳим аст.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Шарҳи амри озмуни «Илм-фурӯғи маърифат»",
    "source": "https://www.president.tj/node/30035"
  },
  {
    "id": 39,
    "img": "assets/hero/09-suhanroni.jpg",
    "topic": "истеъдод",
    "quote": "Дарёфт ва муаррифии истеъдодҳои нав ба рушди ҷомеа хизмат мекунад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Шарҳи амри озмуни «Илм-фурӯғи маърифат»",
    "source": "https://www.president.tj/node/30035"
  },
  {
    "id": 40,
    "img": "assets/hero/10-nishon-tojikiston.jpg",
    "topic": "китоб",
    "quote": "Ҳангоми баҳогузорӣ ба маҳорати хондан ва аз худ кардан бартарӣ дода мешавад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 12,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Амри озмуни «Фурӯғи субҳи доноӣ китоб аст»",
    "source": "https://president.tj/node/22436"
  },
  {
    "id": 41,
    "img": "assets/hero/01-president-official.jpg",
    "topic": "китоб",
    "quote": "Аъзои фаъоли китобхона будан ва маҳорати қироат низ ба назар гирифта мешавад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Амри озмуни «Фурӯғи субҳи доноӣ китоб аст»",
    "source": "https://president.tj/node/22436"
  },
  {
    "id": 42,
    "img": "assets/hero/02-istiqlol-flag.jpg",
    "topic": "ватандӯстӣ",
    "quote": "Эҳтиром ба таъриху фарҳанги қадимаи тоҷикон ҳисси худшиносиро тақвият медиҳад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Президенти Тоҷикистон",
    "source": "https://president.tj/node/24948"
  },
  {
    "id": 43,
    "img": "assets/hero/03-vahdat-diplomacy.jpg",
    "topic": "маърифат",
    "quote": "Баланд бардоштани сатҳи саводу маърифат яке аз ҳадафҳои муҳим мебошад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 12,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Президенти Тоҷикистон",
    "source": "https://president.tj/node/24948"
  },
  {
    "id": 44,
    "img": "assets/hero/04-kishovarzi.jpg",
    "topic": "илм",
    "quote": "Тавсеаи ҷаҳонбинии илмиву техникӣ барои пешрафти ҷомеа зарур аст.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Президенти Тоҷикистон",
    "source": "https://president.tj/node/24948"
  },
  {
    "id": 45,
    "img": "assets/hero/05-president-young.jpg",
    "topic": "донишгоҳ",
    "quote": "Донишгоҳи миллӣ маркази бузурги таълимию илмӣ ба ҳисоб меравад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Ифтитоҳи бинои нави таълимӣ",
    "source": "https://www.president.tj/node/24997"
  },
  {
    "id": 46,
    "img": "assets/hero/06-zaboni-millat.jpg",
    "topic": "маориф",
    "quote": "Донишгоҳ дар рушду такомули соҳаи илму маориф мақоми хоса дорад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 12,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Ифтитоҳи бинои нави таълимӣ",
    "source": "https://www.president.tj/node/24997"
  },
  {
    "id": 47,
    "img": "assets/hero/07-chehrahoyi-mondagor.jpg",
    "topic": "ҷавонон",
    "quote": "Тарбияи ҷавонони худогоҳу худшинос ва мутахассисони варзида вазифаи муҳим аст.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Ифтитоҳи бинои нави таълимӣ",
    "source": "https://www.president.tj/node/24997"
  },
  {
    "id": 48,
    "img": "assets/hero/08-davlatdori.jpg",
    "topic": "фарҳанг",
    "quote": "Фарҳанг ҳастии миллат аст.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Филми «Фарҳанг — ҳастии миллат аст»",
    "source": "https://www.president.tj/president/films/filmography/58"
  },
  {
    "id": 49,
    "img": "assets/hero/09-suhanroni.jpg",
    "topic": "фарҳанг",
    "quote": "Рушди фарҳанг яке аз бахшҳои муҳими соҳаи иҷтимоии кишвар мебошад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 12,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Филми «Фарҳанг — ҳастии миллат аст»",
    "source": "https://www.president.tj/president/films/filmography/58"
  },
  {
    "id": 50,
    "img": "assets/hero/10-nishon-tojikiston.jpg",
    "topic": "ватан",
    "quote": "Барои ободии Ватан ҳар як шаҳрванди бонангу номус бояд саҳм гузорад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Суханронӣ ба ифтихори 25-солагии истиқлолият",
    "source": "https://www.president.tj/node/12958"
  },
  {
    "id": 51,
    "img": "assets/hero/01-president-official.jpg",
    "topic": "китоб",
    "quote": "Баланд бардоштани завқи китобхонӣ ба рушди нерӯи зеҳнии ҷомеа мусоидат мекунад.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Амри озмуни «Фурӯғи субҳи доноӣ китоб аст»",
    "source": "https://president.tj/node/22436"
  },
  {
    "id": 52,
    "img": "assets/hero/02-istiqlol-flag.jpg",
    "topic": "дониш",
    "quote": "Омӯзиши илму дониш ва касбу ҳунар роҳи хизмат ба Ватан аст.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 12,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Суханронӣ бахшида ба Рӯзи дониш",
    "source": "https://president.tj/node/9731.20"
  },
  {
    "id": 53,
    "img": "assets/hero/03-vahdat-diplomacy.jpg",
    "topic": "ваҳдат",
    "quote": "Сулҳу оромӣ ва суботи сиёсӣ асоси пешрафти кишвар мебошанд.",
    "color": "#FFFFFF",
    "fontSize": 18,
    "displayDuration": 10,
    "fontFamily": "'Noto Serif', serif",
    "sourceTitle": "Президенти Тоҷикистон",
    "source": "https://president.tj/event_by_theme/internal_politics/national_unity/20983"
  }
];
